### PR TITLE
상품 이미지 관련 로직 수정

### LINKED ISSUE #116: 상품 이미지 관련 로직 수정
## AS-IS
현재 상품 등록 / 수정시 어떤 이미지가 썸네일 이미지인지 명확히 나타내지 않고 단순히 첫 번째 이미지를 썸네일 이미지로 지정하고 있다.
이때 나타나는 문제는 다음과 같다.
- 이렇게 되면 상품 수정시 썸네일 이미지 삭제후 새로운 들어온 이미지의 첫 번째를 썸네일로 할 지, 기존 남은 이미지의 첫 번째를  썸네일로 할 지 결정해야 한다.

## TO-BE
프론트엔드 단에서 썸네일 이미지를 지정하고 넘겨주도록 결정했기 때문에 이에 따른 로직을 수정한다.

### PR DESCRIPTION
**Pull request by 23Yong**
## Issues
- #116 

## What is this PR? 👓
상품 등록/수정시 썸네일 이미지를 따로 받는 기능에 대한 PR입니다.

## Key changes 🔑
- 상품 등록 시 썸네일 이미지를 따로 받도록 수정
- 상품 수정 시 썸네일을 수정해야하면 썸네일을 수정, 그렇지 않으면 Null로 받도록 구현
- REST Docs를 위한 테스트코드 작성

## To reviewers 👋
- REST Docs 때문에 add lines가 늘어나네요..ㅠ
- 그래도 본 로직은 얼마 없습니다..!

### CODE REVIEW

**Comment by 23Yong** [comment]
### 📝 테스트 커버리지 리포트
|File|Coverage [87.44%]|:green_apple:|
|:-|:-:|:-:|
|[ItemService.java](https://github.com/masters2023-project-03-second-hand/second-hand-max-be-b/blob/654e9db4a6f195cbb07e502afb79d294f7e36288/src%2Fmain%2Fjava%2Fkr%2Fcodesquad%2Fsecondhand%2Fapplication%2Fitem%2FItemService.java)|92.28%|:green_apple:|
|[Item.java](https://github.com/masters2023-project-03-second-hand/second-hand-max-be-b/blob/654e9db4a6f195cbb07e502afb79d294f7e36288/src%2Fmain%2Fjava%2Fkr%2Fcodesquad%2Fsecondhand%2Fdomain%2Fitem%2FItem.java)|91.29%|:green_apple:|
|[ItemController.java](https://github.com/masters2023-project-03-second-hand/second-hand-max-be-b/blob/654e9db4a6f195cbb07e502afb79d294f7e36288/src%2Fmain%2Fjava%2Fkr%2Fcodesquad%2Fsecondhand%2Fpresentation%2FItemController.java)|57.5%|:green_apple:|

|Total Project Coverage|81.43%|:green_apple:|
|:-|:-:|:-:|

**Comment by 23Yong** [comment]
### 📝 테스트 커버리지 리포트
|File|Coverage [87.44%]|:green_apple:|
|:-|:-:|:-:|
|[ItemService.java](https://github.com/masters2023-project-03-second-hand/second-hand-max-be-b/blob/ad55a17c561f61e8337fbe82364ae856a0f77230/src%2Fmain%2Fjava%2Fkr%2Fcodesquad%2Fsecondhand%2Fapplication%2Fitem%2FItemService.java)|92.28%|:green_apple:|
|[Item.java](https://github.com/masters2023-project-03-second-hand/second-hand-max-be-b/blob/ad55a17c561f61e8337fbe82364ae856a0f77230/src%2Fmain%2Fjava%2Fkr%2Fcodesquad%2Fsecondhand%2Fdomain%2Fitem%2FItem.java)|91.29%|:green_apple:|
|[ItemController.java](https://github.com/masters2023-project-03-second-hand/second-hand-max-be-b/blob/ad55a17c561f61e8337fbe82364ae856a0f77230/src%2Fmain%2Fjava%2Fkr%2Fcodesquad%2Fsecondhand%2Fpresentation%2FItemController.java)|57.5%|:green_apple:|

|Total Project Coverage|81.43%|:green_apple:|
|:-|:-:|:-:|

**Comment by 23Yong** [comment]
### 📝 테스트 커버리지 리포트
|File|Coverage [87.44%]|:green_apple:|
|:-|:-:|:-:|
|[ItemService.java](https://github.com/masters2023-project-03-second-hand/second-hand-max-be-b/blob/bcc77796827bdef73f2ac462ea4f396738b23e4b/src%2Fmain%2Fjava%2Fkr%2Fcodesquad%2Fsecondhand%2Fapplication%2Fitem%2FItemService.java)|92.28%|:green_apple:|
|[Item.java](https://github.com/masters2023-project-03-second-hand/second-hand-max-be-b/blob/bcc77796827bdef73f2ac462ea4f396738b23e4b/src%2Fmain%2Fjava%2Fkr%2Fcodesquad%2Fsecondhand%2Fdomain%2Fitem%2FItem.java)|91.29%|:green_apple:|
|[ItemController.java](https://github.com/masters2023-project-03-second-hand/second-hand-max-be-b/blob/bcc77796827bdef73f2ac462ea4f396738b23e4b/src%2Fmain%2Fjava%2Fkr%2Fcodesquad%2Fsecondhand%2Fpresentation%2FItemController.java)|57.5%|:green_apple:|

|Total Project Coverage|81.43%|:green_apple:|
|:-|:-:|:-:|

**Comment by 23Yong** [comment]
### 📝 테스트 커버리지 리포트
|File|Coverage [87.44%]|:green_apple:|
|:-|:-:|:-:|
|[ItemService.java](https://github.com/masters2023-project-03-second-hand/second-hand-max-be-b/blob/95e5f5c8a92f61d39b989f070f068f1ba9e14046/src%2Fmain%2Fjava%2Fkr%2Fcodesquad%2Fsecondhand%2Fapplication%2Fitem%2FItemService.java)|92.28%|:green_apple:|
|[Item.java](https://github.com/masters2023-project-03-second-hand/second-hand-max-be-b/blob/95e5f5c8a92f61d39b989f070f068f1ba9e14046/src%2Fmain%2Fjava%2Fkr%2Fcodesquad%2Fsecondhand%2Fdomain%2Fitem%2FItem.java)|91.29%|:green_apple:|
|[ItemController.java](https://github.com/masters2023-project-03-second-hand/second-hand-max-be-b/blob/95e5f5c8a92f61d39b989f070f068f1ba9e14046/src%2Fmain%2Fjava%2Fkr%2Fcodesquad%2Fsecondhand%2Fpresentation%2FItemController.java)|57.5%|:green_apple:|

|Total Project Coverage|81.43%|:green_apple:|
|:-|:-:|:-:|

**Review by he2joojo — APPROVED** [review]
테스트코드까지 수정하셨네요! 수고하셨습니다~!

**Pull request merged**
